name: the_music
description: A offline music player.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # State management
  provider: ^6.1.2
  # Audio playback
  just_audio: ^0.9.42
  # Beautiful icons
  cupertino_icons: ^1.0.8
  # For Google Fonts
  google_fonts: ^6.2.1
  # NEW: To fetch songs from device
  on_audio_query: ^2.9.0
  # NEW: To handle permissions
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # Add this package
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # Since we use on_audio_query which requires minSdk 21
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true